In [1]:
import numpy as np
import pandas as pd

In [2]:
def getNewRow(player1, player2, winner, p1set, p2set, p1game, p2game, p1score, p2score, server, pts, char, tourney):
    flag = 0
    if char == '/':
        if server == 1:
            server = 2
        elif server == 2:
            server = 1
        flag = 1
    elif char == ';':
        if p1score == 45:
            p1game = p1game + 1
        elif p2score == 45:
            p2game = p2game + 1
        elif p1score == 0:
            p1game = p1game + 1
        elif p2score == 0:
            p2game = p2game + 1
        p1score = 0
        p2score = 0
        if server == 1:
            server = 2
        elif server == 2:
            server = 1
        flag = 1
        
    elif char == '.':
        if p1game > p2game:
            p1set = p1set + 1
        elif p1game < p2game:
            p2set = p2set + 1
        else:
            #print player1, player2, str(p1game) + '-' + str(p2game), str(p1score) + '-' + str(p2score)
            if p1score > p2score:
                p1set = p1set + 1
            elif p1score < p2score:
                p2set = p2set + 1
            if (p1score + p2score) % 4 >= 2:
                if server == 1:
                    server = 2
                elif server == 2:
                    server = 1
        p1game = 0
        p2game = 0
        p1score = 0
        p2score = 0
        if server == 1:
            server = 2
        elif server == 2:
            server = 1  
        flag = 1
    elif p1game == 6 and p2game == 6 and \
    ((tourney not in ["Men'sAustralianOpen","Men'sAustralianOpen.",'MensAustralianOpen', 'MensAustralianOpen.html',
                     "Men'sFrenchOpen", "Men'sFrenchOpen.",'MensFrenchOpen', 'MensFrenchOpen.html',
                     "Gentlemen'sWimbledonSingles", "Gentlemen'sWimbledonSingles.","Gentlemen'sWimbledonSingles.html",
                     #"Men'sUSOpen", "Men'sUSOpen.","Men'sUSOpen.html",
                     'DavisCup','DavisCup-Live', 'DavisCup.html', 'DavisCupLive']) \
     or p1set != 2 or p2set != 2):
        if server == 1:
            if char in ['S','A']:
                p1score = p1score + 1
            elif char in ['R','D']:
                p2score = p2score + 1
        elif server == 2:
            if char in ['S','A']:
                p2score = p2score + 1
            elif char in ['R','D']:
                p1score = p1score + 1    
    elif server == 1:
        if char in ['S','A']:
            if p2score != 45:                    
                p1score = pts[(pts.index(p1score)+1) % len(pts)]
            else:
                p2score = 40
        elif char in ['R','D']:
            if p1score != 45:
                p2score = pts[(pts.index(p2score)+1) % len(pts)]
            else:
                p1score = 40
    elif server == 2:
        if char in ['S','A']:
            if p1score != 45:                    
                p2score = pts[(pts.index(p2score)+1) % len(pts)]
            else:
                p1score = 40
        elif char in ['R','D']:
            if p2score != 45:
                p1score = pts[(pts.index(p1score)+1) % len(pts)]
            else:
                p2score = 40
    return [player1, player2, winner, p1set, p2set, p1game, p2game, p1score, p2score, server, pts, char, flag]

In [4]:
def tourDataSet(raw_data, three_set=True, five_set=False):
    master_data = []
    for i,row in raw_data.iterrows():
        five_set_tourneys = ["Men'sAustralianOpen","Men'sAustralianOpen.",'MensAustralianOpen', 'MensAustralianOpen.html',
                     "Men'sFrenchOpen", "Men'sFrenchOpen.",'MensFrenchOpen', 'MensFrenchOpen.html',
                     "Gentlemen'sWimbledonSingles", "Gentlemen'sWimbledonSingles.","Gentlemen'sWimbledonSingles.html",
                     "Men'sUSOpen", "Men'sUSOpen.","Men'sUSOpen.html"]
        only_both = ['DavisCup','DavisCup-Live', 'DavisCup.html', 'DavisCupLive',
                     "Men'sAustralianOpenWildcardPlayoff"]
        
        pts = [0,15,30,40,45]
        player1 = row['server1']
        player2 = row['server2']
        winner = row['winner']
        score = row['score']
        year = row['date'].split(' ')[-1]
        tourney = row['tny_name']
        server = 1
        p1set,p2set,p1game,p2game,p1score,p2score = 0,0,0,0,0,0
        
        eligible = True
        if three_set == True and five_set == False:
            if tourney in five_set_tourneys or tourney in only_both:
                eligible = False
        if three_set == False and five_set == True:
            if tourney not in five_set_tourneys or tourney in only_both:
                eligible = False
        
        if eligible:
            master_data.append([player1, player2, winner, p1set, p2set, p1game, p2game, p1score, p2score,
                            server, pts, '', score, year, tourney, i])
            for char in row['pbp']:
                newrow = getNewRow(player1, player2, winner, p1set, p2set, 
                                   p1game, p2game, p1score, p2score, server, pts, char, tourney)
                flag = newrow[-1]
                if flag == 0:
                    master_data.append(newrow[:-1] + [score, year, tourney, i])
                elif flag == 1:
                    master_data[-1] = newrow[:-1] + [score, year, tourney, i]
                player1, player2, winner, p1set, p2set, p1game, p2game, p1score, p2score, server, pts, char = newrow[:-1]
            master_data.pop()
        
    return pd.DataFrame(master_data,columns=['Player 1', 'Player 2', 'Winner', 'p1Set', 'p2Set', 'p1Game', 'p2Game', 
                                             'p1Score', 'p2Score', 'Server','Points','Result','Score',
                                             'Year','Tourney','MatchNum'])

In [14]:
pbp_2015 = pd.read_csv('tennis_pointbypoint-master/pbp_matches_atp_main_current.csv')
pbp_archive = pd.read_csv('tennis_pointbypoint-master/pbp_matches_atp_main_archive.csv')
pbp_2015_q = pd.read_csv('tennis_pointbypoint-master/pbp_matches_atp_qual_current.csv')
pbp_archive_q = pd.read_csv('tennis_pointbypoint-master/pbp_matches_atp_qual_archive.csv')
pbp_2015_ch = pd.read_csv('tennis_pointbypoint-master/pbp_matches_ch_main_current.csv')
pbp_archive_ch = pd.read_csv('tennis_pointbypoint-master/pbp_matches_ch_main_archive.csv')
pbp_2015_q_ch = pd.read_csv('tennis_pointbypoint-master/pbp_matches_ch_qual_current.csv')
pbp_archive_q_ch = pd.read_csv('tennis_pointbypoint-master/pbp_matches_ch_qual_archive.csv')


data_15 = tourDataSet(pbp_2015)
data_archive = tourDataSet(pbp_archive.loc[[x not in [2165,2381,2543] for x in pbp_archive.index.values]],three_set=True,five_set=False)
#data_15_q = tourDataSet(pbp_2015_q)
#data_archive_q = tourDataSet(pbp_archive_q)
data_15_ch = tourDataSet(pbp_2015_ch[[x not in challenger_15_idx for x in pbp_2015_ch.index.values]])
data_archive_ch = tourDataSet(pbp_archive_ch[[x not in challenger_archive_idx for x in pbp_archive_ch.index.values]])
#data_15_q_ch = tourDataSet(pbp_2015_q_ch[[x not in challenger_15_q_idx for x in pbp_2015_q_ch.index.values]])
#data_archive_q_ch = tourDataSet(pbp_archive_q_ch[[x not in challenger_archive_q_idx for x in pbp_archive_q_ch.index.values]])

all_point_data = pd.concat([data_15,data_archive,#data_15_q,data_archive_q,
                            data_15_ch,data_archive_ch,#data_15_q_ch,data_archive_q_ch
                           ],axis=0)

In [7]:
all_game_states = {
    (0,0,1): 'Start of Game',
    (0,0,2): 'Start of Game',
    (15,0,1): 'Server 15-0',
    (0,15,2): 'Server 15-0',
    (0,15,1): 'Server 0-15',
    (15,0,2): 'Server 0-15',
    (15,15,1): 'Server 15-15',
    (15,15,2): 'Server 15-15',
    (30,0,1): 'Server 30-0',
    (0,30,2): 'Server 30-0',
    (0,30,1): 'Server 0-30',
    (30,0,2): 'Server 0-30',
    (30,15,1): 'Server 30-15',
    (15,30,2): 'Server 30-15',
    (15,30,1): 'Server 15-30',
    (30,15,2): 'Server 15-30',
    (30,30,1): 'Server 30-30',
    (30,30,2): 'Server 30-30',
    (40,0,1): 'Server 40-0',
    (0,40,2): 'Server 40-0',
    (40,15,1): 'Server 40-15',
    (15,40,2): 'Server 40-15',
    (40,30,1): 'Server 40-30',
    (30,40,2): 'Server 40-30',
    (0,40,1): 'Server 0-40',
    (40,0,2): 'Server 0-40',
    (15,40,1): 'Server 15-40',
    (40,15,2): 'Server 15-40',
    (30,40,1): 'Server 30-40',
    (40,30,2): 'Server 30-40',
    (40,40,1): 'Server 40-40',
    (40,40,2): 'Server 40-40',
    (45,40,1): 'Server AD-40',
    (40,45,2): 'Server AD-40',
    (40,45,1): 'Server 40-AD',
    (45,40,2): 'Server 40-AD'
}

In [8]:
def tiebreak_state(state):
    p1,p2,server = state
    if p1 >= 6 and p2 >=6:
        if p1 > p2 and server == 1:
            return 'Server 7-6'
        elif p1 > p2 and server == 2:
            return 'Server 6-7'
        elif p1 < p2 and server == 1:
            return 'Server 6-7'
        elif p1 < p2 and server == 2:
            return 'Server 7-6'
        else:
            return 'Server 6-6'
    elif server == 1:
        return 'Server ' + str(p1)+'-'+str(p2)
    elif server == 2:
        return 'Server ' + str(p2)+'-'+str(p1)

In [9]:
coordinate_states = {
    'Start of Game': (0,0),
    'Server 15-0': (1,1),
    'Server 0-15': (1,-1),
    'Server 15-15': (2,0),
    'Server 30-0': (2,2),
    'Server 0-30': (2,-2),
    'Server 30-15': (3,1),
    'Server 15-30': (3,-1),
    'Server 30-30': (4,0),
    'Server 40-0': (3,3),
    'Server 40-15': (4,2),
    'Server 40-30': (5,1),
    'Server 0-40': (3,-3),
    'Server 15-40': (4,-2),
    'Server 30-40': (5,-1),
    'Server 40-40': (6,0),
    'Server AD-40': (7,1),
    'Server 40-AD': (7,-1)
}

In [10]:
def tiebreak_coordinates(game_state):
    if game_state not in coordinate_states.keys():
        print game_state#[7:]
        g1, g2 = game_state[7:].split('-')
        #print g1, g2
        return (int(g1)+int(g2), int(g1)-int(g2))
    else:
        return coordinate_states[game_state]

In [15]:
states = [(x,y,z) for x,y,z in zip(all_point_data['p1Score'],all_point_data['p2Score'],all_point_data['Server'])]
all_point_data['Game State'] = [all_game_states[x] if x in all_game_states.keys() else 'Tiebreak' for x in states]
all_point_data['Server Winner'] = [x == y for x,y in zip(all_point_data['Winner'],all_point_data['Server'])]
all_point_data['Game Score Server View'] = [str(x)+'-'+str(y) if z == 1 else str(y)+'-'+str(x)
                                           for x,y,z in zip(all_point_data['p1Game'],all_point_data['p2Game'], 
                                                            all_point_data['Server'])]
all_point_data['Set Score Server View'] = [str(x)+'-'+str(y) if z == 1 else str(y)+'-'+str(x)
                                           for x,y,z in zip(all_point_data['p1Set'],all_point_data['p2Set'], 
                                                            all_point_data['Server'])]

all_point_data['Game State New'] = [tiebreak_state(x) if y == '6-6' else z for x,y,z in zip(states,
                                                                                     all_point_data['Game Score Server View'],
                                                                                     all_point_data['Game State'])]

#all_point_data['Game State New'] = [tiebreak_state(x) if (y == '6-6' and (v != '2-2' or 
                                    #                                      w in ["Men'sUSOpen", "Men'sUSOpen.","Men'sUSOpen.html"]))
                                    #else z for v,w,x,y,z in zip( all_point_data['Set Score Server View'],
                                    #                        all_point_data['Tourney'],
                                    #                        states,                  
                                    #                        all_point_data['Game Score Server View'],
                                    #                        all_point_data['Game State'])]

#new_game_score = []
#for w,x,y in zip(all_point_data['Set Score Server View'],all_point_data['Game Score Server View'],all_point_data['Tourney']):
#    game1, game2 = x.split('-')
#    if w == '2-2' and int(game1) >= 6 and int(game2) >= 6 and y not in ["Men'sUSOpen", "Men'sUSOpen.","Men'sUSOpen.html"]:
#        if int(game1) == int(game2):
#            new_game_score.append('All Square from 6-6 5th Set')
#        elif int(game1) > int(game2):
#            new_game_score.append('Up 1 from 6-6 5th Set')
#        elif int(game1) < int(game2):
#            new_game_score.append('Down 1 from 6-6 5th Set')
#    else:
#        new_game_score.append(x)
#all_point_data['Game Score Server View'] = new_game_score

In [236]:
score_state_all = pd.DataFrame(all_point_data.groupby\
                                (['Set Score Server View','Game Score Server View', 
                                     'Game State New']).count()['Player 1'])
score_state_sum = pd.DataFrame(all_point_data.groupby(['Set Score Server View','Game Score Server View', 
                                     'Game State New', 'Server Winner']).count()['Player 1'])

In [237]:
all_results = []
for set_score, game_score, game_state in score_state_all.index.values:
    #print set_score, game_score, game_state
   
    try:
        x, y = tiebreak_coordinates(game_state)
        if game_score == '6-6':
            if x % 4 == 1 or x % 4 == 2:
                all_results.append((set_score,game_score,'Serving',game_state[7:]+ ' (R)', 
                            1.0*float(score_state_sum.loc[(set_score, game_score, game_state, True)])/
                            float(score_state_all.loc[(set_score,game_score,game_state)]),
                            int(score_state_all.loc[(set_score,game_score,game_state)]),
                            x, y))
            else:
                all_results.append((set_score,game_score,'Serving',game_state[7:]+ ' (S)', 
                            1.0*float(score_state_sum.loc[(set_score, game_score, game_state, True)])/
                            float(score_state_all.loc[(set_score,game_score,game_state)]),
                            int(score_state_all.loc[(set_score,game_score,game_state)]),
                            x, y))
        elif 'Server' in game_state:
            all_results.append((set_score,game_score,'Serving',game_state[7:], 
                            1.0*float(score_state_sum.loc[(set_score, game_score, game_state, True)])/
                            float(score_state_all.loc[(set_score,game_score,game_state)]),
                            int(score_state_all.loc[(set_score,game_score,game_state)]),
                            x, y))
        else:
            all_results.append((set_score,game_score,'Serving',game_state, 
                            1.0*float(score_state_sum.loc[(set_score, game_score, game_state, True)])/
                            float(score_state_all.loc[(set_score,game_score,game_state)]),
                            int(score_state_all.loc[(set_score,game_score,game_state)]),
                            x, y))
            
        if 'Start of Game' not in game_state:
            score1, score2 = game_state[7:].split('-')
            new_score = score2+'-'+score1   
        else:
            new_score = game_state
        
        if game_score == 'Up 1 from 6-6 5th Set':
            newgscore = 'Down 1 from 6-6 5th Set'
        elif game_score == 'Down 1 from 6-6 5th Set':
            newgscore = 'Up 1 from 6-6 5th Set'
        elif game_score == 'All Square from 6-6 5th Set':
            newgscore = game_score
        else:
            gscore1, gscore2 = game_score.split('-')
            newgscore = gscore2+'-'+gscore1
            
        sscore1, sscore2 = set_score.split('-')
        newsscore = sscore2+'-'+sscore1
        
        if game_score == '6-6':
            if x % 4 == 1 or x % 4 == 2:
                new_score = new_score + ' (S)'
            else:
                new_score = new_score + ' (R)'
        
        all_results.append((newsscore,newgscore,'Returning',new_score, 
                            1.0 - 1.0*float(score_state_sum.loc[(set_score, game_score, game_state, True)])/
                            float(score_state_all.loc[(set_score,game_score,game_state)]),
                            int(score_state_all.loc[(set_score,game_score,game_state)]),
                            x, -1*y))
    except KeyError:
        x, y = tiebreak_coordinates(game_state)
        if game_score == '6-6':
            if x % 4 == 1 or x % 4 == 2:
                all_results.append((set_score, game_score, 'Serving',game_state[7:]+ ' (R)', 0.,
                            int(score_state_all.loc[(set_score,game_score,game_state)]), x, y))
            else:
                all_results.append((set_score, game_score, 'Serving',game_state[7:]+ ' (S)', 0.,
                            int(score_state_all.loc[(set_score,game_score,game_state)]), x, y))
        elif 'Server' in game_state:
            all_results.append((set_score, game_score, 'Serving',game_state[7:], 0.,
                            int(score_state_all.loc[(set_score,game_score,game_state)]), x, y))
        else:
            all_results.append((set_score, game_score, 'Serving',game_state, 0.,
                            int(score_state_all.loc[(set_score,game_score,game_state)]), x, y))
        
        #print game_state
        if 'Start of Game' not in game_state:
            score1, score2 = game_state[7:].split('-')
            new_score = score2+'-'+score1   
        else:
            new_score = game_state
        
        if game_score == 'Up 1 from 6-6 5th Set':
            newgscore = 'Down 1 from 6-6 5th Set'
        elif game_score == 'Down 1 from 6-6 5th Set':
            newgscore = 'Up 1 from 6-6 5th Set'
        elif game_score == 'All Square from 6-6 5th Set':
            newgscore = game_score
        else:
            gscore1, gscore2 = game_score.split('-')
            newgscore = gscore2+'-'+gscore1
        sscore1, sscore2 = set_score.split('-')
        newsscore = sscore2+'-'+sscore1
        
        if game_score == '6-6':
            if x % 4 == 1 or x % 4 == 2:
                new_score = new_score + ' (S)'
            else:
                new_score = new_score + ' (R)'
        
        all_results.append((newsscore, newgscore, 'Returning',new_score, 1.,
                            int(score_state_all.loc[(set_score,game_score,game_state)]), x, -1*y))

Server 0-0
Server 0-1
Server 0-2
Server 0-3
Server 0-4
Server 0-5
Server 0-6
Server 1-0
Server 1-1
Server 1-2
Server 1-3
Server 1-4
Server 1-5
Server 1-6
Server 2-0
Server 2-1
Server 2-2
Server 2-3
Server 2-4
Server 2-5
Server 2-6
Server 3-0
Server 3-1
Server 3-2
Server 3-3
Server 3-4
Server 3-5
Server 3-6
Server 4-0
Server 4-1
Server 4-2
Server 4-3
Server 4-4
Server 4-5
Server 4-6
Server 5-0
Server 5-1
Server 5-2
Server 5-3
Server 5-4
Server 5-5
Server 5-6
Server 6-0
Server 6-1
Server 6-2
Server 6-3
Server 6-4
Server 6-5
Server 6-6
Server 6-7
Server 7-6
Server 0-0
Server 0-1
Server 0-2
Server 0-3
Server 0-4
Server 0-5
Server 0-5
Server 0-6
Server 0-6
Server 1-0
Server 1-1
Server 1-2
Server 1-3
Server 1-4
Server 1-5
Server 1-5
Server 1-6
Server 1-6
Server 2-0
Server 2-1
Server 2-2
Server 2-3
Server 2-4
Server 2-5
Server 2-6
Server 3-0
Server 3-1
Server 3-2
Server 3-3
Server 3-4
Server 3-5
Server 3-6
Server 3-6
Server 4-0
Server 4-1
Server 4-2
Server 4-3
Server 4-4
Server 4-5
Server 4-6
Server 5-0
Server 5-1
Server 5-2
Server 5-3
Server 5-4
Server 5-5
Server 5-6
Server 6-0
Server 6-1
Server 6-2
Server 6-3
Server 6-4
Server 6-5
Server 6-6
Server 6-7
Server 7-6
Server 0-0
Server 0-1
Server 0-2
Server 0-2
Server 0-3
Server 0-3
Server 0-4
Server 0-4
Server 0-5
Server 0-5
Server 0-6
Server 0-6
Server 1-0
Server 1-1
Server 1-2
Server 1-3
Server 1-4
Server 1-4
Server 1-5
Server 1-5
Server 1-6
Server 1-6
Server 2-0
Server 2-0
Server 2-1
Server 2-2
Server 2-3
Server 2-3
Server 2-4
Server 2-4
Server 2-5
Server 2-5
Server 2-6
Server 2-6
Server 3-0
Server 3-1
Server 3-2
Server 3-3
Server 3-3
Server 3-4
Server 3-5
Server 3-5
Server 3-6
Server 3-6
Server 4-0
Server 4-1
Server 4-1
Server 4-2
Server 4-3
Server 4-4
Server 4-5
Server 4-5
Server 4-6
Server 4-6
Server 5-1
Server 5-1
Server 5-2
Server 5-2
Server 5-3
Server 5-4
Server 5-4
Server 5-5
Server 5-5
Server 5-6
Server 5-6
Server 6-1
Server 6-2
Server 6-2
Server 6-3
Server 6-4
Server 6-5
Server 6-6
Server 6-7
Server 6-7
Server 7-6
Server 0-0
Server 0-1
Server 0-2
Server 0-3
Server 0-4
Server 0-4
Server 0-5
Server 0-6
Server 1-0
Server 1-1
Server 1-2
Server 1-3
Server 1-4
Server 1-5
Server 1-6
Server 2-0
Server 2-1
Server 2-2
Server 2-3
Server 2-4
Server 2-5
Server 2-6
Server 3-0
Server 3-1
Server 3-2
Server 3-3
Server 3-4
Server 3-5
Server 3-6
Server 4-0
Server 4-1
Server 4-2
Server 4-3
Server 4-4
Server 4-5
Server 4-6
Server 5-0
Server 5-1
Server 5-2
Server 5-3
Server 5-4
Server 5-5
Server 5-6
Server 6-0
Server 6-1
Server 6-2
Server 6-3
Server 6-4
Server 6-5
Server 6-6
Server 6-7
Server 7-6
Server 0-0
Server 0-1
Server 0-2
Server 0-3
Server 0-4
Server 0-5
Server 0-5
Server 0-6
Server 0-6
Server 1-0
Server 1-1
Server 1-2
Server 1-3
Server 1-4
Server 1-5
Server 1-6
Server 1-6
Server 2-0
Server 2-1
Server 2-2
Server 2-3
Server 2-4
Server 2-5
Server 2-6
Server 3-0
Server 3-1
Server 3-2
Server 3-3
Server 3-4
Server 3-5
Server 3-6
Server 4-0
Server 4-1
Server 4-2
Server 4-3
Server 4-4
Server 4-5
Server 4-6
Server 5-0
Server 5-1
Server 5-2
Server 5-3
Server 5-4
Server 5-5
Server 5-6
Server 6-0
Server 6-1
Server 6-2
Server 6-3
Server 6-4
Server 6-5
Server 6-6
Server 6-7
Server 7-6
Server 0-0
Server 0-1
Server 0-2
Server 0-3
Server 0-4
Server 0-4
Server 0-5
Server 0-5
Server 0-6
Server 0-6
Server 1-0
Server 1-1
Server 1-2
Server 1-3
Server 1-4
Server 1-5
Server 1-5
Server 1-6
Server 1-6
Server 2-0
Server 2-1
Server 2-2
Server 2-3
Server 2-4
Server 2-5
Server 2-6
Server 2-6
Server 3-0
Server 3-1
Server 3-2
Server 3-3
Server 3-4
Server 3-5
Server 3-6
Server 3-6
Server 4-0
Server 4-1
Server 4-2
Server 4-3
Server 4-4
Server 4-5
Server 4-6
Server 4-6
Server 5-1
Server 5-2
Server 5-3
Server 5-4
Server 5-5
Server 5-6
Server 6-1
Server 6-2
Server 6-3
Server 6-4
Server 6-5
Server 6-6
Server 6-7
Server 7-6
Server 0-0
Server 0-1
Server 0-2
Server 0-3
Server 0-4
Server 0-5
Server 0-6
Server 1-0
Server 1-1
Server 1-2
Server 1-3
Server 1-4
Server 1-5
Server 1-6
Server 2-0
Server 2-1
Server 2-2
Server 2-3
Server 2-4
Server 2-5
Server 2-6
Server 3-0
Server 3-1
Server 3-2
Server 3-3
Server 3-4
Server 3-5
Server 3-6
Server 4-0
Server 4-1
Server 4-2
Server 4-3
Server 4-4
Server 4-5
Server 4-6
Server 5-1
Server 5-2
Server 5-3
Server 5-4
Server 5-5
Server 5-6
Server 6-1
Server 6-2
Server 6-3
Server 6-4
Server 6-5
Server 6-6
Server 6-7
Server 7-6
Server 0-0
Server 0-1
Server 0-2
Server 0-3
Server 0-4
Server 0-5
Server 0-6
Server 0-6
Server 1-0
Server 1-1
Server 1-2
Server 1-3
Server 1-4
Server 1-5
Server 1-6
Server 2-0
Server 2-1
Server 2-2
Server 2-3
Server 2-4
Server 2-5
Server 2-6
Server 3-0
Server 3-1
Server 3-2
Server 3-3
Server 3-4
Server 3-5
Server 3-6
Server 4-0
Server 4-1
Server 4-2
Server 4-3
Server 4-4
Server 4-5
Server 4-6
Server 5-0
Server 5-1
Server 5-2
Server 5-3
Server 5-4
Server 5-5
Server 5-6
Server 6-0
Server 6-1
Server 6-2
Server 6-3
Server 6-4
Server 6-5
Server 6-6
Server 6-7
Server 7-6
Server 0-0
Server 0-1
Server 0-2
Server 0-2
Server 0-3
Server 0-3
Server 0-4
Server 0-4
Server 1-0
Server 1-1
Server 1-2
Server 1-2
Server 1-4
Server 1-4
Server 1-5
Server 1-5
Server 2-0
Server 2-1
Server 2-2
Server 2-2
Server 2-3
Server 2-4
Server 2-5
Server 2-5
Server 3-0
Server 3-1
Server 3-3
Server 3-4
Server 3-5
Server 3-5
Server 3-6
Server 3-6
Server 4-1
Server 4-3
Server 4-4
Server 4-5
Server 4-6
Server 4-6
Server 5-1
Server 5-2
Server 5-3
Server 5-4
Server 5-5
Server 5-6
Server 5-6
Server 6-1
Server 6-2
Server 6-4
Server 6-5
Server 6-6
Server 6-7
Server 7-6

In [246]:
sum_data = pd.DataFrame(all_results,columns=['Set Score','Game Score','Serving at Start of Game?','Point Score','% Win',
                                             'Number of Instances','Points Elapsed','Y'])
sum_data['Stdev'] = [((x*(1-x))/y)**0.5 for x,y in zip(sum_data['% Win'],sum_data['Number of Instances'])]
sum_data.to_csv('Match_Probs_best5_50_50.csv')
sum_data['Game Score'].unique()

array(['0-0', '0-1', '1-0', '0-2', '2-0', '0-3', '3-0', '0-4', '4-0',
       '0-5', '5-0', '1-1', '1-2', '2-1', '1-3', '3-1', '1-4', '4-1',
       '1-5', '5-1', '2-2', '2-3', '3-2', '2-4', '4-2', '2-5', '5-2',
       '3-3', '3-4', '4-3', '3-5', '5-3', '4-4', '4-5', '5-4', '5-5',
       '5-6', '6-5', '6-6', 'All Square from 6-6 5th Set',
       'Down 1 from 6-6 5th Set', 'Up 1 from 6-6 5th Set'], dtype=object)

In [16]:
bad_states = all_point_data[((all_point_data['Game State'] == 'Tiebreak') & 
                            (all_point_data['Game Score Server View'] != '6-6')) |
                            ([x in ['4-6', '0-6', '6-4', '4-7', '8-4', '4-8','7-6', '6-3',
                                    '7-4', '5-7', '7-5', '6-7', '2-6', '1-6'] for x in all_point_data['Game Score Server View']]) |
                            ([x in ['2-0','0-2'] for x in all_point_data['Set Score Server View']])]
challenger_tour_15_idx = []
challenger_tour_15_q_idx = []
challenger_tour_archive_idx = []
challenger_tour_archive_q_idx = []

for i,row in bad_states.iterrows():
    #print 'Challenger' in row['Year']
    if 'Challenger' in row['Tourney'] and 'Qualifying' not in row['Tourney'] and '15' in row['Year']:
        challenger_tour_15_idx.append(row['MatchNum'])
    elif 'Challenger' in row['Tourney'] and 'Qualifying' not in row['Tourney'] and '15' not in row['Year']:
        challenger_tour_archive_idx.append(row['MatchNum'])
    elif 'Challenger' in row['Tourney'] and 'Qualifying' in row['Tourney'] and '15' in row['Year']:
        challenger_tour_15_q_idx.append(row['MatchNum'])
    elif 'Challenger' in row['Tourney'] and 'Qualifying' in row['Tourney'] and '15' not in row['Year']:
        challenger_tour_archive_q_idx.append(row['MatchNum'])

challenger_15_idx = np.unique(challenger_tour_15_idx)
challenger_15_q_idx = np.unique(challenger_tour_15_q_idx)
challenger_archive_idx = np.unique(challenger_tour_archive_idx)
challenger_archive_q_idx = np.unique(challenger_tour_archive_q_idx)

In [20]:
challenger_archive_idx

array([], dtype=float64)

In [247]:
sum_data

,Set Score,Game Score,Serving at Start of Game?,Point Score,% Win,Number of Instances,Points Elapsed,Y,Stdev
0,0-0,0-0,Serving,0-15,0.493220,590,1,-1,0.020583
1,0-0,0-0,Returning,15-0,0.506780,590,1,1,0.020583
2,0-0,0-0,Serving,0-30,0.427313,227,2,-2,0.032834
3,0-0,0-0,Returning,30-0,0.572687,227,2,2,0.032834
4,0-0,0-0,Serving,0-40,0.365854,82,3,-3,0.053191
5,0-0,0-0,Returning,40-0,0.634146,82,3,3,0.053191
6,0-0,0-0,Serving,15-0,0.570826,1186,1,1,0.014372
7,0-0,0-0,Returning,0-15,0.429174,1186,1,-1,0.014372
8,0-0,0-0,Serving,15-15,0.516689,749,2,0,0.018259
9,0-0,0-0,Returning,15-15,0.483311,749,2,0,0.018259
10,0-0,0-0,Serving,15-30,0.459799,398,3,-1,0.024982
11,0-0,0-0,Returning,30-15,0.540201,398,3,1,0.024982
12,0-0,0-0,Serving,15-40,0.457895,190,4,-2,0.036145
13,0-0,0-0,Returning,40-15,0.542105,190,4,2,0.036145
14,0-0,0-0,Serving,30-0,0.605000,800,2,2,0.017283
15,0-0,0-0,Returning,0-30,0.395000,800,2,-2,0.017283
16,0-0,0-0,Serving,30-15,0.555405,740,3,1,0.018267
17,0-0,0-0,Returning,15-30,0.444595,740,3,-1,0.018267
18,0-0,0-0,Serving,30-30,0.499051,527,4,0,0.021780
19,0-0,0-0,Returning,30-30,0.500949,527,4,0,0.021780
20,0-0,0-0,Serving,30-40,0.476048,334,5,-1,0.027327
21,0-0,0-0,Returning,40-30,0.523952,334,5,1,0.027327
22,0-0,0-0,Serving,40-0,0.618705,556,3,3,0.020598
23,0-0,0-0,Returning,0-40,0.381295,556,3,-3,0.020598
24,0-0,0-0,Serving,40-15,0.567026,649,4,2,0.019450
25,0-0,0-0,Returning,15-40,0.432974,649,4,-2,0.019450
26,0-0,0-0,Serving,40-30,0.539499,519,5,1,0.021879
27,0-0,0-0,Returning,30-40,0.460501,519,5,-1,0.021879
28,0-0,0-0,Serving,40-40,0.493581,701,6,0,0.018883
29,0-0,0-0,Returning,40-40,0.506419,701,6,0,0.018883
...,...,...,...,...,...,...,...,...,...
13092,2-2,Up 1 from 6-6 5th Set,Serving,0-30,0.666667,3,2,-2,0.272166
13093,2-2,Down 1 from 6-6 5th Set,Returning,30-0,0.333333,3,2,2,0.272166
13094,2-2,Up 1 from 6-6 5th Set,Serving,15-0,0.933333,15,1,1,0.064406
13095,2-2,Down 1 from 6-6 5th Set,Returning,0-15,0.066667,15,1,-1,0.064406
13096,2-2,Up 1 from 6-6 5th Set,Serving,15-15,1.000000,11,2,0,0.000000
13097,2-2,Down 1 from 6-6 5th Set,Returning,15-15,0.000000,11,2,0,0.000000
13098,2-2,Up 1 from 6-6 5th Set,Serving,15-30,0.800000,5,3,-1,0.178885
13099,2-2,Down 1 from 6-6 5th Set,Returning,30-15,0.200000,5,3,1,0.178885
13100,2-2,Up 1 from 6-6 5th Set,Serving,15-40,0.000000,1,4,-2,0.000000
13101,2-2,Down 1 from 6-6 5th Set,Returning,40-15,1.000000,1,4,2,0.000000
13102,2-2,Up 1 from 6-6 5th Set,Serving,30-0,0.888889,9,2,2,0.104757
13103,2-2,Down 1 from 6-6 5th Set,Returning,0-30,0.111111,9,2,-2,0.104757
13104,2-2,Up 1 from 6-6 5th Set,Serving,30-15,0.909091,11,3,1,0.086678
13105,2-2,Down 1 from 6-6 5th Set,Returning,15-30,0.090909,11,3,-1,0.086678
13106,2-2,Up 1 from 6-6 5th Set,Serving,30-30,0.875000,8,4,0,0.116927
13107,2-2,Down 1 from 6-6 5th Set,Returning,30-30,0.125000,8,4,0,0.116927
13108,2-2,Up 1 from 6-6 5th Set,Serving,30-40,0.500000,4,5,-1,0.250000
13109,2-2,Down 1 from 6-6 5th Set,Returning,40-30,0.500000,4,5,1,0.250000
13110,2-2,Up 1 from 6-6 5th Set,Serving,40-0,1.000000,7,3,3,0.000000
13111,2-2,Down 1 from 6-6 5th Set,Returning,0-40,0.000000,7,3,-3,0.000000
13112,2-2,Up 1 from 6-6 5th Set,Serving,40-15,1.000000,9,4,2,0.000000
13113,2-2,Down 1 from 6-6 5th Set,Returning,15-40,0.000000,9,4,-2,0.000000
13114,2-2,Up 1 from 6-6 5th Set,Serving,40-30,1.000000,7,5,1,0.000000
13115,2-2,Down 1 from 6-6 5th Set,Returning,30-40,0.000000,7,5,-1,0.000000
13116,2-2,Up 1 from 6-6 5th Set,Serving,40-40,1.000000,7,6,0,0.000000
13117,2-2,Down 1 from 6-6 5th Set,Returning,40-40,0.000000,7,6,0,0.000000
13118,2-2,Up 1 from 6-6 5th Set,Serving,AD-40,1.000000,7,7,1,0.000000
13119,2-2,Down 1 from 6-6 5th Set,Returning,40-AD,0.000000,7,7,-1,0.000000
13120,2-2,Up 1 from 6-6 5th Set,Serving,Start of Game,0.913043,23,0,0,0.058753
13121,2-2,Down 1 from 6-6 5th Set,Returning,Start of Game,0.086957,23,0,0,0.058753

In [260]:
all_point_data['Game Score Server View'].unique()

array(['0-0', '0-1', '1-1', '1-2', '2-2', '2-3', '3-3', '3-4', '4-4',
       '4-5', '5-5', '5-6', '6-6', '1-0', '0-2', '2-1', '1-3', '4-1',
       '1-5', '4-3', '3-2', '2-4', '5-2', '3-1', '1-4', '4-2', '5-4',
       '2-5', '5-3', '3-5', '2-0', '0-3', '5-1', '4-0', '0-5', '3-0',
       '0-4', '6-5', '5-0', '4-6', '3-6', '6-4', '4-7', '1-6', '7-1',
       '1-7', '7-2', '2-8', '5-7', '7-4', '2-6', '6-3', '0-6', '8-4',
       '6-2', '7-6', '6-0', '0-7', '8-0', '6-7', '2-7', '7-3', '3-8',
       '7-0', '0-8', '8-1', '1-9', '10-1', '1-8', '8-2', '2-9', '6-1',
       '3-7', '7-5'], dtype=object)

In [549]:
pbp_2015_ch['pbp'][3289]

'SSSDDS;SARSRRSRRSSRSRSS;SSRSS;SSSRS;RSSSS;SSRSS;DSSSRDRSSRSS;RASSA;RSRSSS;SDSSRA;SRSSS;SRRSSS;R/SA/SR/SS/SR.RASAA;SSSDRDRSSRSS;SSRSS;AASS;RSSSS;RASSA;SRSRSS;SSRSA;RSSRSA;SS;SRADSA;ASS;S/SS/SR/RS/R.SRRRR;SSSA;RSRRR;DSRRSSRD;RRSSSRSS;SSSS;RRDR;SRSSS'

# Tree Visualization

In [120]:
from ete3 import Tree

# Generate a random tree (yule process)
t = Tree()
t.populate(8, names_library=list('ABCDEFGHIJKL'), random_branches=True)

print(t.get_ascii(attributes=['name', 'support'], show_internal=True))

                                    /-G, 0.317295090011
                     /, 0.67147483089
                    |              |                /-F, 0.886301747353
     /, 0.127051245391              \, 0.517452281784
    |               |                               \-E, 0.889885718141
    |               |
    |                \-L, 0.0230225853836
-, 1.0
    |                                /-K, 0.799702440701
    |                /, 0.657441858459
    |               |                \-J, 0.42443504932
     \, 0.265000334682
                    |                /-I, 0.981435233951
                     \, 0.304196593633
                                     \-H, 0.414208780864

In [244]:
sum_data.ix[0:60,]

,Set Score,Game Score,Serving at Start of Game?,Point Score,% Win,Number of Instances,Points Elapsed,Y
0,0-0,0-0,Serving,0-15,0.493220,590,1,-1
1,0-0,0-0,Returning,15-0,0.506780,590,1,1
2,0-0,0-0,Serving,0-30,0.427313,227,2,-2
3,0-0,0-0,Returning,30-0,0.572687,227,2,2
4,0-0,0-0,Serving,0-40,0.365854,82,3,-3
5,0-0,0-0,Returning,40-0,0.634146,82,3,3
6,0-0,0-0,Serving,15-0,0.570826,1186,1,1
7,0-0,0-0,Returning,0-15,0.429174,1186,1,-1
8,0-0,0-0,Serving,15-15,0.516689,749,2,0
9,0-0,0-0,Returning,15-15,0.483311,749,2,0
10,0-0,0-0,Serving,15-30,0.459799,398,3,-1
11,0-0,0-0,Returning,30-15,0.540201,398,3,1
12,0-0,0-0,Serving,15-40,0.457895,190,4,-2
13,0-0,0-0,Returning,40-15,0.542105,190,4,2
14,0-0,0-0,Serving,30-0,0.605000,800,2,2
15,0-0,0-0,Returning,0-30,0.395000,800,2,-2
16,0-0,0-0,Serving,30-15,0.555405,740,3,1
17,0-0,0-0,Returning,15-30,0.444595,740,3,-1
18,0-0,0-0,Serving,30-30,0.499051,527,4,0
19,0-0,0-0,Returning,30-30,0.500949,527,4,0
20,0-0,0-0,Serving,30-40,0.476048,334,5,-1
21,0-0,0-0,Returning,40-30,0.523952,334,5,1
22,0-0,0-0,Serving,40-0,0.618705,556,3,3
23,0-0,0-0,Returning,0-40,0.381295,556,3,-3
24,0-0,0-0,Serving,40-15,0.567026,649,4,2
25,0-0,0-0,Returning,15-40,0.432974,649,4,-2
26,0-0,0-0,Serving,40-30,0.539499,519,5,1
27,0-0,0-0,Returning,30-40,0.460501,519,5,-1
28,0-0,0-0,Serving,40-40,0.493581,701,6,0
29,0-0,0-0,Returning,40-40,0.506419,701,6,0
...,...,...,...,...,...,...,...,...
31,0-0,0-0,Returning,AD-40,0.593407,273,7,1
32,0-0,0-0,Serving,AD-40,0.549065,428,7,1
33,0-0,0-0,Returning,40-AD,0.450935,428,7,-1
34,0-0,0-0,Serving,Start of Game,0.545045,1776,0,0
35,0-0,0-0,Returning,Start of Game,0.454955,1776,0,0
36,0-0,0-1,Serving,0-15,0.360444,541,1,-1
37,0-0,1-0,Returning,15-0,0.639556,541,1,1
38,0-0,0-1,Serving,0-30,0.270000,200,2,-2
39,0-0,1-0,Returning,30-0,0.730000,200,2,2
40,0-0,0-1,Serving,0-40,0.228261,92,3,-3
41,0-0,1-0,Returning,40-0,0.771739,92,3,3
42,0-0,0-1,Serving,15-0,0.437980,911,1,1
43,0-0,1-0,Returning,0-15,0.562020,911,1,-1
44,0-0,0-1,Serving,15-15,0.400602,664,2,0
45,0-0,1-0,Returning,15-15,0.599398,664,2,0
46,0-0,0-1,Serving,15-30,0.367521,351,3,-1
47,0-0,1-0,Returning,30-15,0.632479,351,3,1
48,0-0,0-1,Serving,15-40,0.280000,175,4,-2
49,0-0,1-0,Returning,40-15,0.720000,175,4,2
50,0-0,0-1,Serving,30-0,0.465986,588,2,2
51,0-0,1-0,Returning,0-30,0.534014,588,2,-2
52,0-0,0-1,Serving,30-15,0.412829,608,3,1
53,0-0,1-0,Returning,15-30,0.587171,608,3,-1
54,0-0,0-1,Serving,30-30,0.371681,452,4,0
55,0-0,1-0,Returning,30-30,0.628319,452,4,0
56,0-0,0-1,Serving,30-40,0.318841,276,5,-1
57,0-0,1-0,Returning,40-30,0.681159,276,5,1
58,0-0,0-1,Serving,40-0,0.481297,401,3,3
59,0-0,1-0,Returning,0-40,0.518703,401,3,-3
60,0-0,0-1,Serving,40-15,0.461233,503,4,2

In [282]:
golden_data = pd.read_csv('Match_Probs_50_50.csv')
golden_data = golden_data.drop(golden_data.columns[[0]], axis=1) 
for i,row in golden_data.iterrows():
    if '(R)' in row['Point Score']:
        if row['Serving?'] == 'Serving':
            golden_data.ix[i,'Point Score'] = row['Point Score'][:-3] + '(S)'
            golden_data.ix[i,'Serving?'] = 'Returning'
    if '(S)' in row['Point Score']:
        if row['Serving?'] == 'Returning':
            golden_data.ix[i,'Point Score'] = row['Point Score'][:-3] + '(R)'
            golden_data.ix[i,'Serving?'] = 'Serving'
golden_data.to_csv('Match_Probs_50_50.csv')

In [283]:
golden_data = pd.read_csv('Match_Probs_50_50.csv')
golden_data[(golden_data['Serving?'] == 'Serving') & 
(golden_data['Game Score'] == '6-6') &
(golden_data['Point Score'] == '7-6 (R)')]

,Unnamed: 0,Set Score,Game Score,Serving?,Point Score,% Win,Number of Instances,Points Elapsed,Y
1467,1467,0-0,6-6,Serving,7-6 (R),0.596140,1347,13,1
2937,2937,1-0,6-6,Serving,7-6 (R),0.856618,544,13,1
4407,4407,0-1,6-6,Serving,7-6 (R),0.317910,670,13,1
5877,5877,1-1,6-6,Serving,7-6 (R),0.662651,415,13,1

In [26]:
all_point_data.to_csv('All Point Data.csv')